In [1]:
#First install numpy and run this here
import numpy as np

In [5]:
#Examples of how to use list
a = [2,3,4,5,6]
print(a)
print(a[1])
print(a[0:3])
print(a[-1])

[2, 3, 4, 5, 6]
3
[2, 3, 4]
6


In [9]:
#Examples of numpy implimentation
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a[1:])
print(a[:-2])
a[2] = 10
print(a)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[2 3 4 5]
[1 2 3]
[ 1  2 10  4  5]


In [13]:
#Examples of numpy implimentation
a_mul = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(a_mul[0])
print(a_mul[0,1])
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

[1 2 3]
2
(3, 3)
2
9
int64


In [23]:
a = np.array([[1,2,3],
              [4,"Hello",6],
              [7,8,9]])

print(a)
print(a.dtype)
print(type(a[0][0]))
print(a[0][0].dtype)
print(a[1,1])

[['1' '2' '3']
 ['4' 'Hello' '6']
 ['7' '8' '9']]
<U21
<class 'numpy.str_'>
<U1
Hello


In [26]:
d = {'1':'A'}
a = np.array([[1,2,3],
              [4,d,6],
              [7,8,"Hello"]])

print(a.dtype)
print(type(a[1][0]))

object
<class 'int'>


In [31]:
a_mul = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]],dtype="<U2")

print(a.dtype)
print(type(a[1][0]))

object
<class 'int'>


In [33]:
#To create a numpy shape with one number 
a = np.full((2,3,4),9)
print(a)


[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [35]:
a = np.zeros((3,5,2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [36]:
#This is to reserve the space into empty
a = np.empty((5,5,5))
print(a)

[[[1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]]

 [[1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]]

 [[1.40698517e-311 1.40698517e-311 1.40698517e-311 1.40698517e-311
   1.40698517e-311]
  [1.40698517e-311 1.40698517e-311 1.40

In [42]:
x_values = np.arange(0,1005,5)
print(x_values)
x_values = np.linspace(0,1000,2)
print(x_values)
x_values = np.linspace(0,1000,100)
print(x_values)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [46]:
#These are some values that are useful to fill our list and remove
print(np.nan)
print(np.inf)
print(np.isnan(np.nan))
print(np.isinf(np.inf))
print(np.sqrt(-1))
print(np.array([10])/0)

nan
inf
True
True
nan
[inf]


C:\Users\mohit\AppData\Local\Temp\ipykernel_27032\3467862719.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\mohit\AppData\Local\Temp\ipykernel_27032\3467862719.py:6: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [53]:
l1 = [1,2,3,4,5,6]
l2 = [7,8,9,10,11,12]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5)
print(l2 * 5)
#this is normal addition in python
print(l1 + l2)
#This is with numpy
print(a1 + a2)
#here we can do arthemetic operations on list
#with numpy library, but nott possible in normal list
print(a1 - a2)
#You can also do in matrix form
a1 = np.array([1,2,3])
a2 = np.array([[1],
               [2]])

print(a1 + a2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
[7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, 12]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[[2 3 4]
 [3 4 5]]


In [56]:
#Any 
a = np.array([[1,2,3],
               [4,5,6]])

print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [60]:
a1 = np.array([1,2,3])
a1 = np.append(a,[7,8,9])
a1 = np.insert(a,3,[4,5,6])

print(a1)

[1 2 3 4 5 6 4 5 6]


In [64]:
a = np.array([[1,2,3],
               [4,5,6]])

print(np.delete(a,1))
print(np.delete(a,3))
print(np.delete(a,4))
#For second row also
print(np.delete(a,0,0))
#this is for column
print(np.delete(a,1,1))

[1 3 4 5 6]
[1 2 3 5 6]
[1 2 3 4 6]
[[4 5 6]]
[[1 3]
 [4 6]]


In [85]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

print(a.shape)
print(a.reshape((5,4)))
print(a.reshape((20,)))
print(a.reshape((2,2,5)))

a = a.reshape(5,4)
print(a)

a = a.resize(10,2)
print(a)

print(a.flatten())
print(a.ravel())

var1 = a.ravel()
var1[2] = 100
print(var1)
print(a)

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
None


In [89]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

print(a.transpose())
#or
print(a.T)
#To swap
print(a.swapaxes(0,1))

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [95]:
a1 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
a2 = np.array([[11,12,13,14,15],
              [16,17,18,19,20]])

a = np.concatenate((a1,a2),axis = 1)
print(a)
a = np.stack((a1,a2))
print(a)
a = np.vstack((a1,a2))
print(a)
a = np.hstack((a1,a2))
print(a)



[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [101]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

print(np.split(a,2,axis = 0))
print(np.split(a,1,axis = 1))

print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
1
20
10.5
5.766281297335398
210
10.5


In [110]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

number = np.random.randint(100)
print(number)
#Also
number = np.random.randint(100,size = (2,3,4))
print(number)
#Can also do this means giving range
number = np.random.randint(90,100,size = (2,3,4))
print(number)
number = np.random.binomial(10,p=0.5,size=(5,10))
print(number)
number = np.random.normal(loc = 170,scale=15,size = (5,10))
print(number)
number = np.random.choice([1,2,3,4,5,6],size=(5,10))
print(number)

82
[[[85 66 13  2]
  [46  3  6 50]
  [71 76 76 82]]

 [[80 45 35 15]
  [40 46  6 98]
  [13 38  4 61]]]
[[[90 96 93 91]
  [96 93 90 93]
  [98 98 97 94]]

 [[98 95 99 91]
  [90 91 94 98]
  [97 99 98 99]]]
[[6 7 5 5 5 3 6 4 5 5]
 [7 2 5 5 8 6 3 5 7 4]
 [7 5 3 5 3 5 6 1 5 5]
 [6 8 3 7 8 3 7 5 2 6]
 [5 6 4 3 4 5 3 6 3 5]]
[[153.76570588 167.07786712 147.8888195  171.07237301 163.83813689
  180.30500899 150.67267197 155.08179233 181.72879957 167.01954798]
 [172.20519504 201.41652906 147.78467421 157.39227524 172.61549231
  185.46916538 176.07696348 187.23327972 167.96052124 182.28579135]
 [175.41470743 181.66549529 175.90500739 166.80296439 137.92410294
  183.06390696 157.32056351 135.59664805 161.84409752 193.04636793]
 [176.53198661 150.32040685 172.8212518  140.58294165 157.11411387
  172.46247677 166.814245   153.53066039 134.74028846 179.87985217]
 [152.44593087 177.29647706 201.09337845 189.68181339 157.88611223
  173.15677105 164.09548159 170.43630637 181.51699989 166.18358497]]
[[4 3

In [114]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

np.save("Myarray.npy",a)
a = np.load("Myarray.npy")
print(a)

np.savetxt("myarray.csv",a,delimiter=",")
print(a)

np.loadtxt("myarray.csv",a,delimiter=",")
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


TypeError: Cannot construct a dtype from an array